apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: owl-red
  namespace: fleet-default
spec:
  repo: https://github.com/d0ntblink/owl.red.git
  branch: main
  clientSecretName: owl-red-github-auth
  paths:
    - gitops/technitium
    - gitops/metallb
    - gitops/cert-manager
    - gitops/traefik
    - gitops/dashboards
