apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-technitium-admin
  namespace: technitium-namespace
spec:
  organizationId: "202b0b27-b135-44cd-a969-b43a003ad670"
  secretName: technitium-admin
  onlyMappedSecrets: true
  map:
    - bwSecretId: 29f2afc9-11f3-4091-ae83-b448008b8d94
      secretKeyName: admin-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
