apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-technitium-api-token
  namespace: technitium-namespace
spec:
  organizationId: "202b0b27-b135-44cd-a969-b43a003ad670"
  secretName: technitium-api-token
  onlyMappedSecrets: true
  map:
    - bwSecretId: e4771a82-23f7-4435-b75a-b448008b8ddd
      secretKeyName: token
  authToken:
    secretName: bw-auth-token
    secretKey: token
