service:
  type: LoadBalancer
  annotations:
    metallb.io/loadBalancerIPs: "10.0.10.201"

deployment:
  replicas: 3

podDisruptionBudget:
  enabled: true
  minAvailable: 2

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

logs:
  general:
    level: INFO

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.owl.red`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints:
      - websecure
    tls: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
              app.kubernetes.io/instance: traefik-traefik
          topologyKey: kubernetes.io/hostname

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik-traefik

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    http:
      tls:
        enabled: true
