apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-metallb-webhook-cert
  namespace: metallb-system
spec:
  organizationId: "202b0b27-b135-44cd-a969-b43a003ad670"
  secretName: metallb-webhook-cert
  onlyMappedSecrets: true
  map:
    - bwSecretId: cab2e2a8-510e-4565-aeef-b448008b8c7d
      secretKeyName: ca.crt
    - bwSecretId: a81cedb7-9f45-4137-9cd1-b448008b8cc4
      secretKeyName: ca.key
    - bwSecretId: 87ff9de8-252f-44bf-9cc5-b448008b8d09
      secretKeyName: tls.crt
    - bwSecretId: d28dfefb-2a37-447a-8137-b448008b8d50
      secretKeyName: tls.key
  authToken:
    secretName: bw-auth-token
    secretKey: token
