apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-cattle-webhook-ca
  namespace: cattle-system
spec:
  organizationId: "202b0b27-b135-44cd-a969-b43a003ad670"
  secretName: cattle-webhook-ca
  onlyMappedSecrets: true
  map:
    - bwSecretId: 81cfceac-5626-4806-9eef-b448008b825c
      secretKeyName: tls.crt
    - bwSecretId: f2bdcf32-0477-44d7-a08b-b448008b829d
      secretKeyName: tls.key
  authToken:
    secretName: bw-auth-token
    secretKey: token
