apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-tls-rancher-internal-ca
  namespace: cattle-system
spec:
  organizationId: "202b0b27-b135-44cd-a969-b43a003ad670"
  secretName: tls-rancher-internal-ca
  onlyMappedSecrets: true
  map:
    - bwSecretId: a0d7b99b-0949-48ea-8b2e-b448008b8668
      secretKeyName: tls.crt
    - bwSecretId: 2b263d76-f17d-485e-abe9-b448008b86a9
      secretKeyName: tls.key
  authToken:
    secretName: bw-auth-token
    secretKey: token
