apiVersion: v1
kind: ConfigMap
metadata:
  name: technitium-zone-owl-red
  namespace: technitium-namespace
  labels:
    app.kubernetes.io/name: technitium
    app.kubernetes.io/component: dns-zone-source
data:
  owl.red.zone: |
    $ORIGIN owl.red.
    $TTL 300
    @ IN SOA dns.owl.red. hostmaster.owl.red. (
      2026051002 ; serial (update on every record change)
      3600       ; refresh
      600        ; retry
      1209600    ; expire
      300        ; minimum
    )
    @ IN NS dns.owl.red.

    dns             IN A 10.0.10.30
    rancher         IN A 10.0.10.201
    flame           IN A 10.0.10.201
    homepage        IN A 10.0.10.201
    homer           IN A 10.0.10.201
    edge            IN A 10.0.10.1
    switch          IN A 10.0.10.2
    edge.pve        IN A 10.0.10.3
    storage.pve     IN A 10.0.10.4
    nas             IN A 10.0.10.5
    ipmi.storage    IN A 10.0.10.6
    pdu             IN A 10.0.10.7
    cp1.pve         IN A 10.0.10.11
    cp2.pve         IN A 10.0.10.12
    cp3.pve         IN A 10.0.10.13
    worker1.pve     IN A 10.0.10.14
    cp1.k8s         IN A 10.0.10.21
    cp2.k8s         IN A 10.0.10.22
    cp3.k8s         IN A 10.0.10.23
    worker1.k8s     IN A 10.0.10.24
    pdm             IN A 10.0.10.31
    pbs             IN A 10.0.10.33
    ap              IN A 10.0.10.40
