apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-pv-ha
  labels:
    app.kubernetes.io/name: technitium
    app.kubernetes.io/component: storage-ha
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: technitium-local-temp-ha
  hostPath:
    path: /var/lib/technitium-dns-ha
    type: DirectoryOrCreate
