apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-pv
  labels:
    app.kubernetes.io/name: technitium
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: technitium-local-temp
  hostPath:
    path: /var/lib/technitium-dns
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker1-talos
