apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-data-ha
  namespace: technitium-namespace
  labels:
    app.kubernetes.io/name: technitium
    app.kubernetes.io/component: storage-ha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: technitium-local-temp-ha
  volumeName: technitium-pv-ha
