apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-data
  namespace: technitium-namespace
  labels:
    app.kubernetes.io/name: technitium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: technitium-local-temp
  volumeName: technitium-pv
