apiVersion: v1
kind: Service
metadata:
  name: technitium-dns
  namespace: technitium-namespace
  labels:
    app.kubernetes.io/name: technitium
  annotations:
    metallb.io/address-pool: "technitium-vip-pool"
    metallb.io/loadBalancerIPs: "10.0.10.30"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: technitium
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
