apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-cert-manager-webhook-ca
  namespace: cert-manager
spec:
  organizationId: "202b0b27-b135-44cd-a969-b43a003ad670"
  secretName: cert-manager-webhook-ca
  onlyMappedSecrets: true
  map:
    - bwSecretId: 72ae1f22-9217-4fb6-9f40-b448008b86f6
      secretKeyName: ca.crt
    - bwSecretId: 2bb6f15a-7800-4d4b-9ac8-b448008b8738
      secretKeyName: tls.crt
    - bwSecretId: a109ffd1-3689-44d7-bd02-b448008b877f
      secretKeyName: tls.key
  authToken:
    secretName: bw-auth-token
    secretKey: token
